services:
  - type: web
    name: coconut-disease-api
    runtime: python
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn inference.inference.infer:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
